language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - pytest
deploy:
  provider: pypi
  user: xiaowangwindow
  password:
    secure: "Wk5vK+Cfo982sWhG0ufb8gPqUpWeymUtUMwYvHnTvWegK0+BfygWrfR0be03VYIluif8hR6H5FzaDyFs+sNVUc4qQT522FOZXTwHAHl8c3b9d2nlHgB99EgItlysAyuFIoRLAfBPyxAFvqsq7fKQasBSrMPhLxj3u4+gHhc0LgAiJx6T7vghOLrUt1CbSY/z1jYL+9wwMLdVGMPEfDtq3JmXmGhZhLVFNpzJpm9smFr0stP0E/D4qV7l/VyfsGXH1kZDVAwhrGW4s0h0jNIZQ7D3cDd/52u50PVxzINgDt8ZY2bi+zT9mBqmCGWRM0DWouxM6L8j9DJogSXEuj2tH2uymhlWAKiml5WAn+KhLXE50h7WIx9XSHdn1ROrKZXzjM7aed3WtTf4CNeA7xTBTUCGgBYH9fue43xOORTNE5VU5qdAuMNWGt7EVYESS/wFfuu/6MUx6vaOyqXzw/L/XUNsnQ1mVM3mug774RNKKBKijeSqVkK06zK6H3KHeTKogMHxtrI6zAhNpuC0XhpAhWzQIrPPOEXQbREYW1q1o1yVu2t5lVOSuycTTsBRTyHblkY/wfMVIJr4s01IiA3X5BXq7S5g/V9ecLyWRcE2NrnCyYGbMo22WLUC8V3V2+rORxAxMUUqfdUqbWPDCCk4yDxceGnbCuRgQ2MFXBn08iw="
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: xiaowangwindow/scrapy-rotated-cookies